import { StyleSheet } from "react-native";

export const mainStyleSheet = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f0f2f5" },
  coverContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
  avatarContainer: {
    top: 70,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: "#fff",
    backgroundColor: "#e0e0e0",
    marginHorizontal: 'auto',
    marginTop: -40,

  },
  adminName: {
    fontSize: 25,
    fontWeight: "bold",
    color: "#1d2052",
    paddingVertical: 20,
    marginTop: 30,
  },
  adminRole: {
    fontSize: 14,
    color: "#007bff",
    fontWeight: "600",
    marginBottom: 8,
  },
  actionsRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginVertical: 10,
    gap: 16,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 24,
    marginHorizontal: 8,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  actionText: {
    marginLeft: 8,
    color: "#1d2052",
    fontWeight: "bold",
    fontSize: 15,
  },
  section: {
    fontSize: 20,
    fontWeight: "700",
    marginLeft: 18,
    marginVertical: 10,
    color: "#1d2052",
  },
  feed: {
    marginHorizontal: 12,
    marginVertical: 20,
  },
  loading: {
    textAlign: "center",
    color: "#888",
    marginVertical: 8,
  },
  fullScreenForm: {
    flex: 1,
    backgroundColor: "#fff",
    paddingTop: 40,
    paddingHorizontal: 16,
    justifyContent: "center",
  },
  closeButton: {
    position: "absolute",
    top: 40,
    right: 24,
    zIndex: 10,
    backgroundColor: "#f0f2f5",
    borderRadius: 20,
    padding: 4,
    elevation: 2,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginHorizontal: 12,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  emptyIndicator: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  emptyText: {
    marginTop: 8,
    color: "#aaa",
    fontSize: 16,
  },
  userInfoBox: {
    marginTop: 10,
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 12,
    alignSelf: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  userInfoText: {
    fontSize: 14,
    color: "#333",
    marginBottom: 4,
  },
  tabMenu: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 16,
    marginHorizontal: 12,
    marginBottom: 10,
    height: 70,
    marginTop: 10,
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    height: "100%",
  },
  tabItemActive: {
    backgroundColor: "#e0e7ff",
    borderRadius: 16,
  },
  tabText: {
    fontSize: 14,
    color: "#888",
  },
  tabTextActive: {
    color: "#1d2052",
    fontWeight: "600",
  },
});